Default logging
Scan-o-Matic/scanomatic-standalone pull request #48
Opened 2021-10-29 09:56 UTC by local-minimum

Resolves #40 

- Removes own custom logger

Will make new issue for log rotation

2021-11-02 14:44 UTC, skymandr requested changes
Inte riktigt klar, så requestar ändringar så länge (mest saker jag är fundersam över, inget viktigt troligen).

2021-11-02 14:44 UTC, skymandr commented on scanomatic/server/phenotype_effector.py
> +        )
återhållsamt!

2021-11-03 07:24 UTC, local-minimum commented on scanomatic/data_processing/strain_handler.py
> +_logger = Logger("Strain Handler Module")
det e lite varierat mend framförallt bara stora när det e på en klass statiskt

2021-11-03 07:26 UTC, local-minimum commented on scanomatic/io/logger.py
> +def get_logger(name: str, file_path: Optional[str] = None) -> logging.Logger:
jo det används när loggning ska ner på disk. eg, behövs den nog användas överallt eller så i framtiden, men tänker att jag gör en issue för det

2021-11-03 07:28 UTC, local-minimum commented on scanomatic/io/logger.py
> +def get_logger(name: str, file_path: Optional[str] = None) -> logging.Logger:
https://github.com/Scan-o-Matic/scanomatic-standalone/issues/57

2021-11-03 07:32 UTC, local-minimum commented on scanomatic/server/proc_effector.py
> +            get_logger(logger_name, logging_target)
jo den behövs tror jag, för flera olika loggers ska logga till samma fil. eller det e möjligt att det går att lösa inte med `logging.Logger` men `logging.getLogger` givet att allt konfigureras exakt varje gång. SoM har och använder funktionalitet för att parsea loggarna och visa upp dem för användarna. Om en bara lägger på en file handler till en logger så ärver inte den formatteringen en satt upp för standard out.

2021-11-03 07:33 UTC, local-minimum commented on scanomatic/server/phenotype_effector.py
> +        )
syftar du på avsaknad av komma eller ngt annat?

2021-11-03 07:34 UTC, local-minimum commented on scanomatic/io/rpc_client.py
> +    cp = _ClientProxy(host, port, log_level=None)
hmm undra varför ajg tog bort det  där... ser inte korrekt ut.

2021-11-03 07:37 UTC, local-minimum commented on scanomatic/io/rpc_client.py
> +    cp = _ClientProxy(host, port, log_level=None)
och nej den kan aldrig klaga på sånt eftersom log_level skulle kunna användas för att homogenisera signaturen i andra kontext och behövas så även om den inte har funktion här.

2021-11-03 08:49 UTC, skymandr commented on scanomatic/data_processing/strain_handler.py
> +_logger = Logger("Strain Handler Module")
Jag frågar för att det stod `_L`, men nu står `_logger`. Antar att det är rätt som det är nu då?

2021-11-03 08:50 UTC, skymandr commented on scanomatic/server/phenotype_effector.py
> +        )
att du inte gick över till `pathlib` direkt var återhållsamt, men jo, komma saknas också.

2021-11-03 08:51 UTC, skymandr commented on scanomatic/io/rpc_client.py
> +    cp = _ClientProxy(host, port, log_level=None)
Kolla på om det är korrekt då.

2021-11-03 08:51 UTC, skymandr commented on scanomatic/io/rpc_client.py
> +    cp = _ClientProxy(host, port, log_level=None)
Eller, det hade du visst redan gjort.

2021-11-03 08:52 UTC, skymandr commented on scanomatic/server/phenotype_effector.py
> +        )
```suggestion
        logging_target = os.path.join(
            self._feature_job.analysis_directory,
            paths.Paths().phenotypes_extraction_log,
        )
```

2021-11-03 08:53 UTC, skymandr approved these changes
LGTM

2021-11-03 09:09 UTC, local-minimum commented on scanomatic/data_processing/strain_handler.py
> +_logger = Logger("Strain Handler Module")
har försökt migrera mot _logger så långt det går med det undantaget jag nämnde innan

2021-11-03 09:10 UTC, local-minimum commented on scanomatic/server/phenotype_effector.py
> +        )
ah nej försöker vara återhållsam faktiskt 😆

2021-11-03 09:11 UTC, merged